@startuml SportLink

class Utilisateur {
  - {field} id : UUID
  - {field} nomUtilisateur : String
  - {field} courriel : String
  - {field} motDePasse : String
  - {field} dateDeNaissance : String
  - {field} sportsFavoris : List<Sport>
  - {field} disponibilites : List<String>
  - {field} photoProfil : String
}

class Authentification {
    + inscrire(courriel : String, nomUtilisateur : String, motDePasse : String) : Bool
    + connecter(courriel : String, motDePasse : String) : Utilisateur
    + oublierMotDePasse(courriel : String) : void
}

Authentification --> Utilisateur : utilise

class ProfilUtilisateurVueModele {
  - {field} utilisateur : Utilisateur
  - {field} estEnChargement : Bool
  + {method} modifierMotDePasse(nouveauMotDePasse : String) : void
  + {method} chargerUtilisateur() : void
  + {method} modifierProfil(sportsFavoris : List<Sport>, disponibilites : List<String>, photoProfil : String) : void
  + {method} changerPhotoProfil(nouvellePhoto : String) : void
}

class ProfilUtilisateurVue {
  - {field} vueModele : ProfilUtilisateurVueModele
}

ProfilUtilisateurVueModele "1" --* "1" Utilisateur
ProfilUtilisateurVue ..> ProfilUtilisateurVueModele

class Activite {
  - {field} id : UUID
  - {field} sport : Sport
  - {field} intervalleDate : DateInterval 
  - {field} placesDisponibles : Integer
  - {field} niveau : Niveau
  - {field} emplacement : Emplacement
  - {field} messages : List<Message>
  - {field} mode : ModeUtilisateur
}

class ActiviteVueModele {
  - {field} activite : Activite
  - {field} utilisateur : Utilisateur
  + {method} creerActiviteRecreative(date : Date, sport : Sport, places : Integer, debut : String, fin : String, lieu : String) : Activite
  + {method} creerActiviteCompetitif(date : Date, sport : Sport, places : Integer, debut : String, fin : String, lieu : String, niveau : Niveau) : Activite
}

class ActiviteVue {
  - vueModele : ActiviteVueModele
}

ActiviteVue ..> ActiviteVueModele
ActiviteVueModele --> Utilisateur : selon le mode
ActiviteVueModele --> Activite : cree

class Emplacement {
  - {field} nomEmplacement : String
  - {field} coordonnees : CLLocationCoordinate2D
  - {field} sportsDisponibles : List<String>
  - {field} heuresOuvertures : String
  - {field} activites : List<Activite>   
}
'Demander à Louis pour la liste d'activités

class Message {
  - {field} id : UUID
  - {field} contenu : String
  - {field} envoyeA : Date
  - {field} expediteur : Utilisateur
  - {field} idActivite : UUID
}

class MessageVueModele {
  - {field} message : Message
  - {field} estEnChargement : Bool
}

class MessageVue {
  - {field} vueModele : MessageVueModele
}

MessageVueModele "1" --* "1" Message
MessageVue ..> MessageVueModele


class AccueilVueModele {

}

class ExplorerVueModele {

}

class CreerVueModele {

}

class ActivitesVueModele {

}

enum Niveau {
  Debutant
  Intermediaire
  Avance
}

enum Sport {
  Basketball
  Soccer
  Volleyball
  Baseball
  Tennis
  Badminton
  Pickleball
  Waterpolo
  Football
  Rugby
  Ultimate
  Hockey
}

enum ModeUtilisateur {
  Recreatif
  Competitif
}

@enduml